# Streamlit Cloud Secrets Configuration Template
# This file shows the format - add real values in Streamlit Cloud dashboard

# Google Maps API Configuration
GOOGLE_MAPS_API_KEY = "YOUR_GOOGLE_MAPS_API_KEY_GOES_HERE"
GOOGLE_CLOUD_PROJECT = "your-google-cloud-project-id"

# Instructions for Streamlit Cloud:
# 1. Go to your app settings in Streamlit Cloud
# 2. Click "Secrets" tab
# 3. Copy the format above with your REAL API keys
# 4. The format must be: key = "value" (with quotes for strings)

# Never commit real API keys to GitHub!

# Optional: Additional API keys if using separate ones
# GOOGLE_PLACES_API_KEY = "your_places_api_key_here"

# Notes:
# 1. Do NOT commit this file with real API keys
# 2. Add real values in Streamlit Cloud dashboard under "Secrets"
# 3. Format should be: key = "value" (with quotes for strings) 